version: "2.3"
# runtime: nvidia needs version 2 else change standard runtime at host pc

services:

    deep_speech:
        image: deep_speech_german
        network_mode: "host"
        runtime: nvidia
        privileged: true
        shm_size: '16gb'  # needed?
        volumes:
            - .:/DeepSpeech/deepspeech-german/
            - ../DeepSpeech/DeepSpeech.py:/DeepSpeech/DeepSpeech.py
            - ../DeepSpeech/evaluate.py:/DeepSpeech/evaluate.py
            - ../DeepSpeech/util/feeding.py:/DeepSpeech/util/feeding.py
            - ../DeepSpeech/util/evaluate_tools.py:/DeepSpeech/util/evaluate_tools.py
            - ../DeepSpeech/util/flags.py:/DeepSpeech/util/flags.py
            - ../DeepSpeech/data/lm/generate_lm.py:/DeepSpeech/data/lm/generate_lm.py
            - ../DeepSpeech/data/lm/generate_package.py:/DeepSpeech/data/lm/generate_package.py
            - ../checkpoints/:/DeepSpeech/checkpoints/
            - ../data_original/:/DeepSpeech/data_original/
            - ../data_prepared/:/DeepSpeech/data_prepared/
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY
            # - "CUDA_VISIBLE_DEVICES=1"
            - QT_X11_NO_MITSHM=1
            - "PYTHONUNBUFFERED=1"
        command: /bin/bash -i -c 'sleep infinity'